package updater

import (
	"crypto/ed25519"
	"encoding/base64"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// releasePublicKey is the base64-encoded ed25519 public key used to verify
// checksums.txt signatures. Generated by scripts/generate-signing-key.sh.
// The corresponding private key is stored as the RELEASE_SIGNING_KEY GitHub
// Actions secret and used during the release workflow to sign checksums.txt.
//
// Replace this value after generating a real keypair.
var releasePublicKey = "H8oSW6IXPljT/4njuWdRYxS2D8rJxK9qvBza5K3lnA0="

// verifySignatureBytes verifies an ed25519 signature over checksumData
// using the embedded release public key. sigBody is the raw base64-encoded
// signature content (as stored in checksums.txt.sig).
func verifySignatureBytes(checksumData []byte, sigBody []byte) error {
	if releasePublicKey == "UNSIGNED" {
		return fmt.Errorf("release signing key not configured - binary was built without a public key")
	}

	pubKeyBytes, err := base64.StdEncoding.DecodeString(releasePublicKey)
	if err != nil {
		return fmt.Errorf("invalid embedded public key: %w", err)
	}
	if len(pubKeyBytes) != ed25519.PublicKeySize {
		return fmt.Errorf("invalid embedded public key length: %d", len(pubKeyBytes))
	}

	sigB64 := strings.TrimSpace(string(sigBody))
	sig, err := base64.StdEncoding.DecodeString(sigB64)
	if err != nil {
		return fmt.Errorf("invalid signature encoding: %w", err)
	}

	if !ed25519.Verify(ed25519.PublicKey(pubKeyBytes), checksumData, sig) {
		return fmt.Errorf("signature verification failed - checksums.txt may have been tampered with")
	}

	return nil
}

// verifySignature downloads checksums.txt.sig and verifies the ed25519
// signature over checksumData using the embedded public key.
// Returns the raw signature body for optional local caching.
func verifySignature(checksumData []byte, sigURL string, client *http.Client) ([]byte, error) {
	resp, err := client.Get(sigURL)
	if err != nil {
		return nil, fmt.Errorf("failed to download signature: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("signature download returned status %d", resp.StatusCode)
	}

	sigBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read signature: %w", err)
	}

	if err := verifySignatureBytes(checksumData, sigBody); err != nil {
		return nil, err
	}

	return sigBody, nil
}
